version: '3.9'

services:
  python:
    image: ghcr.io/hartmannlight/kit-mensa-discord-bot:latest
    restart: always
    volumes:
      - /opt/docker/mensa-am-adenauerring/logs:/app/logs
    environment:
      - BOT_TOKEN=
      - GUILD=
      - CHANNEL_ID=
      - UPDATE_INTERVAL=
      - TZ=Europe/Berlin
