name: Build Docker image
on:
  push:
    branches:
      - master
      - '*'

  pull_request:
    branches:
      - master
      - '*'

jobs:
  docker:
    name: Push to GitHub Container Registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: "ghcr.io/Hartmannlight/kit-mensa-discord-bot"
          tags: |
            type=sha
            type=ref,event=branch
          flavor: |
            latest=${{ github.ref == 'refs/heads/master' }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push to registry
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          build-args: |
              "GIT_HASH=${{ github.sha }}"
